name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or your source code branch (gh-page is the built branch)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # needed to deploy to GitHub Pages
      id-token: write   # needed for authentication
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
